---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: production
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-bcdd37d2
  image_type: c1.medium
  image_id: ami-e7582d8e
  security_groups:
  - likeme_production_default
  - likeme_production_web
  - likeme_production_web_tools
  spot_instance_request_id: sir-8d6aa232
  external_host: ec2-54-224-194-68.compute-1.amazonaws.com
  external_ip: 54.224.194.68
  internal_host: ip-10-30-149-75.ec2.internal
  internal_ip: 10.30.149.75
  zone: us-east-1b
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
