---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: production
  domain: like-me.info
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-d29da6b1
  image_type: c1.medium
  image_id: ami-e7582d8e
  security_groups:
  - likeme_production_default
  - likeme_production_web
  - likeme_production_web_tools
  external_host: ec2-50-17-69-152.compute-1.amazonaws.com
  external_ip: 50.17.69.152
  internal_host: ip-10-244-222-166.ec2.internal
  internal_ip: 10.244.222.166
  zone: us-east-1d
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
